import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './_shared/nav/Nav';
import {AuthProvider} from '@/app/_util/authContext';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AuthProvider>
      <body className={inter.className}>
      <Nav/>
      {children}
      </body>
    </AuthProvider>
    </html>
  )
}
